apiVersion: apps/v1
kind: Deployment
metadata:
  name: framepack-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: framepack-api
  template:
    metadata:
      labels:
        app: framepack-api
    spec:
      containers:
      - name: framepack-api
        image: sofarc6soat/framepack-api:latest
        ports:
        - containerPort: 81
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: ASPNETCORE_URLS
          value: http://+:81
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: "/health"
            port: 81
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: "/health"
            port: 81
          initialDelaySeconds: 30
          periodSeconds: 10