version: '3.9'

services:
  framepack-api:
    build:
      context: ../../src
      dockerfile: ./Api/Dockerfile
    restart: always
    image: framepack-api
    container_name: framepack-api
    ports:
      - 5000:80
      - 5001:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORTS=443
      - ASPNETCORE_HTTP_PORTS=80
    volumes:
      - ./certs:/https:ro
    networks:
      - framepack-api-network

networks:
  framepack-api-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.172.0.0/16
          gateway: 172.172.0.1
