version: '3.8'

services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    user: root
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

  dynamodb-local-setup:
    container_name: dynamodb-local-setup
    image: amazon/aws-cli
    volumes:
      - "./tests/schemas:/tmp/dynamo"
    environment:
      AWS_ACCESS_KEY_ID: 'AKIA4VDBMBTV5OW266EA'
      AWS_SECRET_ACCESS_KEY: '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'
      AWS_REGION: 'eu-west-1'
